---
nvm_version: v0.33.8
node_versions:
  install:
  - &def_node_ver v9.8.0
  - 8
  default: *def_node_ver
git_options:
  commit.gpgsign: true
  commit.template: >-
    ~/src/github/webknjaz/ansible-gentoo-laptop/roles/gentoo-userspace/files/git-commit.template
  core.repositoryFormatVersion: 1
  gpg.program: gpg2
  pull.ff: only
  push.gpgsign: if-asked
  user.email: wk@sydorenko.org.ua
  user.name: Sviatoslav Sydorenko
  user.signingkey: 9345E8FEA89CA455
vundle:
  self_plugin: VundleVim/Vundle.vim
  bundle_path: ~/.config/nvim/bundle
  self_dir: Vundle.vim
  plugins:
  # fugitive.vim is a Git wrapper for Vim (plugin on GitHub repo)
  - id: tpope/vim-fugitive

  # HTML speedup
  # The sparkup vim script is in a subdirectory of this repo called vim.
  # Pass the path to set the runtimepath properly.
  - id: rstacruz/sparkup
    config:
      rtp: vim/

  #- id: pearofducks/ansible-vim
  - id: MicahElliott/Rocannon

  - id: scrooloose/nerdtree
  - id: altercation/vim-colors-solarized

  - id: jplaut/vim-arduino-ino

  # fuzzy finder :Files
  - id: junegunn/fzf.vim

  # lightline statusline theme
  - id: itchyny/lightline.vim

  # multicursor feature
  - id: terryma/vim-multiple-cursors

  # eunuch.vim: Helpers for UNIX
  - id: tpope/vim-eunuch

  # surround.vim: quoting/parenthesizing made simple
  - id: tpope/vim-surround

  # editorconfig.org
  - id: editorconfig/editorconfig-vim

  # emmet for vim
  - id: mattn/emmet-vim

  # Asynchronous linting/fixing for Vim
  # and Language Server Protocol (LSP) integration
  - id: w0rp/ale

  # show a git diff in the gutter (sign column)
  - id: airblade/vim-gitgutter

  # LaTeX
  - id: lervag/vimtex
  - id: donRaphaco/neotex

  # Python
  - id: davidhalter/jedi-vim

  # TypeScript
  - id: leafgarland/typescript-vim
  - id: HerringtonDarkholme/yats.vim

  # SCSS
  - id: cakebaker/scss-syntax.vim

  # SASS
  - id: tpope/vim-haml
  # - id: shmargum/vim-sass-colors  # causes errors

  # Examples:

  # plugin from http://vim-scripts.org/vim/scripts.html
  #- id: L9

  # Git plugin not hosted on GitHub
  #- id: git://git.wincent.com/command-t.git

  # git repos on your local machine (i.e. when working on your own plugin)
  #- id: file:///home/gmarik/path/to/plugin

  # Install L9 and avoid a Naming conflict if you've already installed a
  # different version somewhere else.
  #- id: ascenator/L9
  #  config:
  #    name: newL9
awesome:
  terminal: kitty
  theme: zenburn
kitty:
  plugins_dir: ~/.config/kitty/plugins
  plugins:
  - name: base16
    src: git://github.com/kdrag0n/base16-kitty.git
    config: colors/base16-darktooth-256.conf
oh_my_zsh:
  theme: spaceship  # default: robbyrussell; was: ys
  custom_themes:
    spaceship: git://github.com/denysdovhan/spaceship-prompt.git
  editor: nvim
  locale: en_US.UTF-8  # uk_UA.UTF-8
  plugins:
  - git
  - pyenv
  - ssh-agent
  - gpg-agent
  - nvm
  - common-aliases
  - docker
  - shrink-path
  - helm
  - kubectl
  - oc
  - sudo
  - systemd
  - tmux
  - websearch
  - yarn
  - screen
  - python
  - pylint
  - pip
  - pep8
  - npm
  - node
  - ng
  - lol
  - last-working-dir
  # custom
  - kitty
  custom_plugins:
    zsh-autosuggestions: git://github.com/zsh-users/zsh-autosuggestions.git
    zsh-syntax-highlighting: git://github.com/zsh-users/zsh-syntax-highlighting.git
    tty-solarized: git://github.com/joepvd/tty-solarized.git
  plugin_settings:
    ssh-agent:
      agent-forwarding: on
      identities: id_rsa id_rsa_encrypted
      #lifetime: 4h  # Forever by default
    tty-solarized:
      theme-shade: dark
code_workspace:
  source_dir: ~/src
  repos:
    - name: github
      fqdn: github.com
      ssh_host_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
      slugs:
      - ahlinc/invoicer
      - aio-libs/aiohttp
      - aio-libs/aiohttp-devtools
      - aio-libs/multidict
      - amol-/dukpy
      - ansible/ansible
      - ansible/ansible-examples
      - ansible/ansible-lint
      - ansible/ansible-lint-action
      - ansible/ansibullbot
      - ansible/foreman-test-container
      - ansible/lightbulb
      - ansible/molecule
      - bcoca/collection
      - benjaminp/six
      - bitprophet/alabaster
      - candlepin/candlepin
      - cherrypy/cheroot
      - cherrypy/cherrypy
      - cherrypy/magicbus
      - dokku/dokku-mariadb
      - EuroPython/ep-config
      - FreeCAD/FreeCAD
      - gentoo/gentoo
      - github-actions-playground/enroll-me
      - gliderlabs/herokuish
      - itkpi/beej-s-guide-to-network
      - jctanner/ansible-reproducers
      - jctanner/gravity
      - joepvd/tty-solarized
      - kpi-web-guild/django-girls-blog-serhii73
      - libgit2/pygit2
      - lxc/python2-lxc
      - lxc/python3-lxc
      - matrixise/europython-config-the-revenant
      - open-craft-guild/aio-feature-flags
      - open-craft-guild/ansible-fedora-laptop
      - open-craft-guild/prze-merge-2017-kurwa
      - open-craft-guild/python-smsfly
      - patron-it/ansible-opencanary
      - patron-it/opencanary
      - pyca/bcrypt
      - PyCQA/baron
      - PyCQA/redbaron
      - pyenv/pyenv
      - PyGithub/PyGithub
      - pypa/auditwheel
      - pypa/browntruck
      - pypa/get-pip
      - pypa/gh-action-pypi-publish
      - pypa/manylinux
      - pypa/pip
      - pypa/pipenv
      - pypa/pipfile
      - pypa/setuptools
      - pypa/setuptools_scm
      - pypa/ssl
      - pypa/twine
      - pypa/virtualenv
      - pypa/warehouse
      - pypa/wheel
      - python/cherry_picker
      - python/core-workflow
      - python/cpython
      - python/miss-islington
      - python/peps
      - python-hyper/h11
      - python-trio/snekomatic
      - python-trio/trustme
      - re-actors/manylinux1_x86_64-action
      - re-actors/pypi-action
      - RedHatOfficial/RedHatOfficial.github.io
      - rtfd/readthedocs-docker-images
      - sanitizers/chronographer-github-app
      - sanitizers/ci-mediator-github-app
      - sanitizers/diactoros-github-app
      - sanitizers/github-bot-tutorial
      - sanitizers/octomachinery
      - sclorg/s2i-python-container
      - sdispater/poetry
      - streetturtle/awesome-wm-widgets
      - takluyver/flit
      - tox-dev/detox
      - tox-dev/gh-action-tox
      - tox-dev/tox
      - travis-ci/dpl
      - travis-ci/travis-yml
      - webknjaz/ansible.module_utils._text
      - webknjaz/ansiwatch-bot
      - webknjaz/check-in
      - webknjaz/docker-freecad-cli
      - webknjaz/docker-freecad-cli-dev
      - webknjaz/fortunate-pkg
      - webknjaz/fqcn_conftest_repro
      - webknjaz/gentoo-overlay
      - webknjaz/mrgall-ansible
      - webknjaz/pypi-deployment
      - webknjaz/talk-drafts
      - webknjaz/talks
      - webknjaz/twitter-reporter
      - willthames/ansible-review
      - yaml/pyyaml
      forked_as:
        amol-/dukpy: webknjaz/dukpy
        ansible/ansible: webknjaz/ansible
        ansible/ansible-lint: webknjaz/ansible-lint
        ansible/ansibullbot: webknjaz/ansibullbot
        ansible/lightbulb: webknjaz/lightbulb
        ansible/molecule: webknjaz/molecule
        benjaminp/six: webknjaz/six
        bitprophet/alabaster: webknjaz/alabaster
        FreeCAD/FreeCAD: webknjaz/FreeCAD
        gentoo/gentoo: webknjaz/gentoo
        gliderlabs/herokuish: webknjaz/herokuish
        jctanner/ansible-reproducers: webknjaz/ansible-reproducers
        jctanner/gravity: webknjaz/gravity
        joepvd/tty-solarized: webknjaz/tty-solarized
        libgit2/pygit2: webknjaz/pygit2
        lxc/python2-lxc: webknjaz/python2-lxc
        lxc/python3-lxc: webknjaz/python3-lxc
        pyca/bcrypt: webknjaz/bcrypt
        PyCQA/baron: webknjaz/baron
        PyCQA/redbaron: webknjaz/redbaron
        pyenv/pyenv: webknjaz/pyenv
        PyGithub/PyGithub: webknjaz/PyGithub
        pypa/browntruck: sanitizers/browntruck
        pypa/pip: webknjaz/pip
        pypa/setuptools: webknjaz/setuptools
        pypa/twine: webknjaz/twine
        pypa/virtualenv: webknjaz/virtualenv
        pypa/warehouse: webknjaz/warehouse
        python/cherry_picker: webknjaz/cherry_picker
        python/core-workflow: webknjaz/core-workflow
        python/cpython: webknjaz/cpython
        python/peps: webknjaz/peps
        python-hyper/h11: webknjaz/h11
        python-trio/snekomatic: webknjaz/snekomatic
        python-trio/trustme: webknjaz/trustme
        RedHatOfficial/RedHatOfficial.github.io: >-
          webknjaz/RedHatOfficial.github.io
        sdispater/poetry: webknjaz/poetry
        streetturtle/awesome-wm-widgets: webknjaz/awesome-wm-widgets
        takluyver/flit: webknjaz/flit
        tox-dev/detox: webknjaz/detox
        tox-dev/tox: webknjaz/tox
        travis-ci/dpl: webknjaz/dpl
        travis-ci/travis-yml: webknjaz/travis-yml
        willthames/ansible-review: webknjaz/ansible-review
        yaml/pyyaml: webknjaz/pyyaml
    - name: bitbucket
      fqdn: bitbucket.org
      ssh_host_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==
      slugs: []
      forked_as: []
    - name: gitlab
      fqdn: gitlab.com
      ssh_host_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsj2bNKTBSpIYDEGk9KxsGh3mySTRgMtXL583qmBpzeQ+jqCMRgBqB98u3z++J1sKlXHWfM9dyhSevkMwSbhoR8XIq/U0tCNyokEi/ueaBMCvbcTHhO7FcwzY92WK4Yt0aGROY5qX2UKSeOvuP4D6TPqKF1onrSzH9bx9XUf2lEdWT/ia1NEKjunUqu1xOB/StKDHMoX4/OKyIzuS0q/T1zOATthvasJFoPrAjkohTyaDUz2LN5JoH839hViyEG82yB+MjcFV5MU3N1l1QL3cVUCh93xSaua1N85qivl+siMkPGbO5xR/En4iEY6K2XPASUEMaieWVNTRCtJ4S8H+9
      - ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFSMqzJeV9rUzU4kWitGjeR4PWSa29SPqJ1fVkhtj3Hw9xjLVXVYrU9QlYWrOLXBpQ6KWjbjTDTdDkoohFzgbEY=
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAfuCHKVTjquxvt6CM6tdG4SLp1Btn/nOeHHE5UOzRdf
      slugs:
      - remak-dva/components-api
      - remak-dva/docker-freecad-cli
      - remak-dva/phex-recutech-mcs
      - remak-dva/tbe-mcs
      forked_as: []
    - name: gitlab-kentigen
      fqdn: gitlab.kentigen.com
      ssh_host_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCbjLW4UyWneMZ7sYg5jcWYdXEh1ePlyrLU+y0GJFC19lM6wQDn6ySrIzVQdbc2B1WFkkGexcPWKA/Sbdjq+0gf7ydyEJ5VqPW4kklqDp5zrhgI3YBKtCm5BK3Ed3t8F+GiBy3L71tVYMrQsraiKM9/roQLLLIPJBEtCvm4BEh838QfxYG45imylKXKaDq5P3YTo03pK1CL3HrDK2Qsqn/JlnuHgC9Q5KAh5PFbX13yS4vXMiyVGQjw6aqks/vIEszJy0LY4r+faEZ/8+1ojsL6FF3I6utoB3UkraoNYVQ2Scpi2vhUB/k/SGi5UWWY1b31o7PaXillarzFQKqvBeOz
      - ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBDe+z2leG8YTRmU4xfMC1zptIqnhYQFcr1WSjuuQRvyQtiXc6Q1y4VAJzb2pnQGJBK/xbw8P+OaLcyNiA03ed0Y=
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKmRAW+xXYH6Rz/UfPYF7+PR4TbbX2867IJsBzFQ0W1+
      slugs:
      - so2019-037_tcl_tk/std-6
      - so2019-037_tcl_tk/std-6-original-tcl
      forked_as: []

ibank_websigner_plugin:
  url: https://ibank.procreditbank.com.ua/websigner-linux.bin
  sha256sum: fbeb4b363fae74e360660a50184b688059b21f2c63c38201abf9417b9e44a8ae
