--- # vim:se ft=ansible:
- name: Install nvm
  git:
    repo: https://github.com/creationix/nvm.git
    dest: ~/.nvm
    version: "{{ nvm_version }}"
- name: Install Nodes  # noqa 301  # FIXME
  shell: "source ~/.nvm/nvm.sh && nvm install {{ item }}"
  with_items: "{{ node_versions.install }}"
- name: Set default Node version  # noqa 301  # FIXME
  shell: "source ~/.nvm/nvm.sh && nvm alias default {{ node_versions.default }}"
