---
vagga_testing: no
emerge_load_average: 4
emerge_jobs_number: 9
abi_x86_targets:
- 64
python_targets:
- 3.7
#- 3.8
#- 3.9
ruby_targets:
- 2.5
- 2.6
- 2.7
video_card_targets:
- intel
- i965
- iris
use_flags_global_enabled:
- kerberos
- luajit
- python
- sasl
- savedconfig
- static-libs
use_flags_global_disabled: []
use_flags_per_package_enabled:
  dev-libs/libdbusmenu:
  - gtk3
  dev-libs/nss:
  - utils
  media-libs/libsdl2:
  - gles2  # dependency of USE-wayland
  media-video/vlc:
  - chromecast
  net-dns/bind-tools:
  - gssapi
  net-misc/spice-gtk:
  - usbredir
  sys-auth/sssd:
  - sudo
  sys-devel/gcc:
  - graphite
  sys-apps/systemd:
  - cgroup-hybrid  # Solves conflict with app-emulation/docker. Refs:
  # https://bugs.gentoo.org/691844
  # https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=9753537cfaf24e80397a0236a169ded2ccc19fdf
  - cryptsetup
  - curl
  - dns-over-tls
  - gnuefi
  - http
  - idn
  - importd
  - lzma
  - nat
  - pkcs11
  - qrcode
  - repart
  - xkb
  sys-libs/glibc:
  - nscd
  sys-libs/zlib:
  - minizip
  x11-misc/redshift:
  - geoclue
use_flags_per_package_disabled:
  app-text/mupdf:
  - static-libs
accept_keywords_per_package:
  =app-shells/rust-zshcomp-9999::rust:
  - >-
    **
#  sys-libs/glibc:  # conflicts with sssd: https://bugs.gentoo.org/737180
#  - -~amd64
essential_ebuilds:
- app-admin/sudo  # privilege escalation
- app-admin/eselect  # alternatives management
- app-portage/eix  # fast portage tree search
- app-portage/gentoolkit  # euse and co.
- app-portage/layman  # needed to manage third-party Git overlays
- dev-vcs/git  # needed to fetch third-party Git overlays
- sys-apps/gptfdisk  # gdisk: https://wiki.gentoo.org/wiki/EFI_System_Partition
- sys-fs/cryptsetup  # LUKS
- sys-fs/exfat-utils  # exFAT support
- sys-fs/dosfstools  # mkfs.fat: https://wiki.gentoo.org/wiki/EFI_System_Partition
- sys-fs/lvm2  # LVM management
- sys-fs/xfsdump  # https://yallalabs.com/linux/how-to-reduce-shrink-the-size-of-a-lvm-partition-formatted-with-xfs-filesystem/
- sys-process/htop  # processes overview
- sys-process/lsof  # htop dep
- www-client/links  # needed to browse web docs from terminal
ebuilds:
- abrt
- sys-power/acpi
- sys-power/acpid
- alacritty
- alsa-utils
- android-tools
- anydesk
- apache-tools
- app-emulation/docker
- app-misc/screen
- arc-theme
- arphicfonts
- artwiz-aleczapka-en
- asciinema
- atop
- awesome
- axel
- bind-tools
- bbswitch  # FIXME: make host-dependent
- bundler
- ccache
- cndrvcups-common-lb
- corefonts
- darktable
- dnsmasq
- dpkg
- dstat
- ebtables
- enchant
- eselect-fontconfig
- fira-code
- font-bh-ttf
- font-bh-type1
- foomatic-db
- foomatic-db-engine
- foomatic-db-ppds
- freefonts
- freerdp
- fuse-exfat
- app-shells/fzf  # CLI fuzzy finder
- genkernel
- gentoo-sources
- grub
# https://blogs.gentoo.org/mgorny/2019/12/19/a-distribution-kernel-for-gentoo/:
- sys-kernel/gentoo-kernel-bin
# https://blogs.gentoo.org/mgorny/2019/12/19/a-distribution-kernel-for-gentoo/:
- sys-kernel/installkernel-systemd-boot
- sys-libs/efivar
- app-shells/gentoo-zsh-completions
- gnome-color-manager
- google-chrome
- gutenprint
- media-gfx/flameshot
- intel-ocl-sdk
- iosevka
- iperf:3
- iptraf-ng
- irssi
- sys-apps/irqbalance
- jq
- jre
- kexec-tools
- kitty
- libfprint
- libinput-gestures
- libgnomecups
- libpod
- libvirt
- light
- linux-firmware
#- lxc
- lxdm
- luajson
- luaposix
- luarocks
- luasocket
- mesa-progs
- neovim
- openbsd-netcat
- networkmanager
- networkmanager-openvpn
- networkmanager-sstp
- nmap
- noto
- noto-emoji
- ntfs3g
- pam_krb5
- parcellite
- pavucontrol
- pcsc-lite
- powerline-symbols
- pulseaudio
- python:3.7
- python:3.8
- pam_u2f
- pam_yubico
- qemu
- qrencode
- quivira
- rawtherapee
- x11-misc/i3lock
- x11-misc/redshift
- rust-bin
- sic
- sshfs
- sssd
- strace
- tcpdump
- tcptraceroute
- telnet-bsd
- termtosvg
- texlive-langcyrillic
- texlive-latexrecommended
- thunar
- thunderbird-bin
- tmux
- traceroute
- ttf-bitstream-vera
- unicode-emoji
- unifont
- usbutils
- vagrant
- app-emulation/virtualbox
- virt-manager
- vlc
- wget2
- wireshark
- wmname
- xautolock
- xflux-gui
- xorg-x11
- yubikey-manager
- zh-kcfonts
- zsh-completions
ebuilds_from_overlays:
  app-crypt/keybase-bin: dmchurch  # TODO: use "keybase" once it supports GUI
  app-editors/vscode-bin: jorgicio
  app-shells/rust-zshcomp: rust
  media-fonts/emojione-color-font: jorgicio
  media-fonts/twemoji-color-font: jorgicio
  x11-themes/materia-theme: jorgicio

unmask_ebuilds: {}

accept_licenses:
  app-editors/vscode-bin: MS-vscode
  dev-util/intel-ocl-sdk: Intel-SDP
  media-fonts/corefonts: MSttfEULA
  media-fonts/font-bh-ttf: bh-luxi
  media-fonts/font-bh-type1: bh-luxi
  media-fonts/freefonts: all-rights-reserved free-noncomm freedist
  net-misc/anydesk: AnyDesk-TOS
  net-print/cndrvcups-common-lb: Canon-UFR-II
  sys-kernel/linux-firmware: linux-fw-redistributable no-source-code
  www-client/google-chrome: google-chrome
  x11-misc/xflux: f.lux

layman_overlays:
- dmchurch
- jorgicio
- rust

ca_certificates:
  RH-legacy-Root-CA:
    filename: legacy
    sha256sum: 59aa5919eccaf4cbf77dbc9ede454a65a9116d85d35447af0c2de2f62123042e
    sha256fingerprint: 14:23:83:73:74:67:0D:8D:13:0B:49:3B:D9:43:D8:CB:68:86:43:FB:0F:B3:72:E3:BE:7D:B7:62:2C:29:AF:E1
  RH-IT-Root-CA:
    filename: RH-IT-Root-CA
    sha256sum: 86479b04ef23e30ba736c83da3f0c9d301beebdc97822521ca500118d3991c79
    sha256fingerprint: 27:09:47:C8:EB:A9:AE:6F:01:79:9F:13:4E:7D:BE:BE:90:2A:0A:2E:09:E1:B8:FD:06:B5:FC:3A:7D:7E:CE:F3

user_pass: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  64616537623134383263656436613531396563343161616561666638386339326430363461363562
  3439303338396262393335643333633833343664326565380a336263663363306331653837623230
  39653236663533313038366335303865373333353763306366346439336134356237333264366336
  3538393665343937360a313730313336306131303632303262333034343236306537383934666230
  32376630623835623538386434303338363436336536626635626464613237643739636333313263
  62616236373564613662663238383335623436613333663238636530333135313962376133316466
  33363739616532633639386632613936353464383634633938306132633266633761333037333835
  33383331373932363038323161626665643339643732313938393462656434636231653238396130
  61653339626464336432343637313362383334663066373430343838333535353863

public_dns_servers:
- 8.8.4.4
- 1.0.0.1
- 8.8.8.8
- 1.1.1.1

corp_dns_servers:
- 10.38.5.26
- 10.64.63.6
- 10.97.120.27
- 10.64.255.25
- 10.35.255.14
- 10.5.30.160
- 10.75.5.25
- 10.11.5.19
- 10.68.5.26

corp_domains:
- ams2.redhat.com
- auth.redhat.com
- brq.redhat.com
- cee.redhat.com
- corp.redhat.com
- devel.redhat.com
- emea.redhat.com
- engineering.redhat.com
- ipa.redhat.com
- paas.redhat.com
- pnt.redhat.com
- rdu.redhat.com
- rdu2.redhat.com
- rhu.redhat.com
- rover.redhat.com
- token.redhat.com
- usersys.redhat.com
- yyz.redhat.com
