---
vagga_testing: no
emerge_load_average: 4
emerge_jobs_number: 9
ebuilds:
- abrt
- acpi
- alacritty
- alsa-utils
- android-tools
- anydesk
- apache-tools
- app-emulation/docker
- app-misc/screen
- arc-theme
- arphicfonts
- asciinema
- atop
- awesome
- axel
- bind-tools
- bbswitch
- bundler
- cndrvcups-common-lb
- dnsmasq
- dpkg
- dstat
- ebtables
- emojione-color-font
- enchant
- exfat-utils
- fira-code
- flameshot
- foomatic-db
- foomatic-db-engine
- foomatic-db-ppds
- freerdp
- fuse-exfat
- fzf
- git
- gentoo-sources
- gentoo-zsh-completions
- gnome-color-manager
- google-chrome
- gutenprint
- htop
- i3lock-color
- intel-ocl-sdk
- iosevka
- iperf:3
- iptraf-ng
- irssi
- jq
- jre
- keybase
- kitty
- layman
- libfprint
- libinput-gestures
- libgnomecups
- libpod
- libvirt
- light
- links
#- lxc
- lxdm
- lsof
- luajson
- luaposix
- luarocks
- luasocket
- materia-theme
- mesa-progs
- neovim
- netcat
- networkmanager
- networkmanager-openvpn
- networkmanager-sstp
- nmap
- noto
- noto-emoji
- ntfs3g
- pam_krb5
- parcellite
- pavucontrol
- pcsc-lite
- powerline-symbols
- pulseaudio
- python:3.6
- python:3.7
- qrencode
- pam_u2f
- pam_yubico
- qemu
- redshift
- rust-bin
- rust-zshcomp
- sic
- sssd
- strace
- symbola
- tcpdump
- tcptraceroute
- telnet-bsd
- termtosvg
- texlive-langcyrillic
- texlive-latexrecommended
- thunar
- thunderbird-bin
- tmux
- traceroute
- twemoji-color-font
- unicode-emoji
- usbutils
- vagrant
- virtualbox-bin
- virt-manager
- visual-studio-code
- vlc
- wget2
- wireshark
- wmname
- xautolock
- xflux-gui
- xorg-x11
- yubikey-manager
- zh-kcfonts
- zsh-completions
ca_certificates:
  RH-legacy-Root-CA:
    filename: legacy
    sha256sum: 59aa5919eccaf4cbf77dbc9ede454a65a9116d85d35447af0c2de2f62123042e
    sha256fingerprint: 14:23:83:73:74:67:0D:8D:13:0B:49:3B:D9:43:D8:CB:68:86:43:FB:0F:B3:72:E3:BE:7D:B7:62:2C:29:AF:E1
  RH-IT-Root-CA:
    filename: RH-IT-Root-CA
    sha256sum: 86479b04ef23e30ba736c83da3f0c9d301beebdc97822521ca500118d3991c79
    sha256fingerprint: 27:09:47:C8:EB:A9:AE:6F:01:79:9F:13:4E:7D:BE:BE:90:2A:0A:2E:09:E1:B8:FD:06:B5:FC:3A:7D:7E:CE:F3
